### ISSUE TITLE
condense CRDS laser controls

### ISSUE THREAD

**Issue by JustinLangridge** [msr-consulting/exscalabar#113]
Only one frequency and duty cycle controlneeded to serve all lasers now.

**Comment by JustinLangridge** [comment]
Given the potential for messing up the crds acquisiton timing when using these contols, this would be good to address during phase 3

**Comment by lo-co** [comment]
I am not following how this messes up anything.  Entering something in one box changes all, right?  So, what is the difference between having one or all?  The idea behind having the UI elements is for future spec'ing.

**Comment by lo-co** [comment]
This is good to go.
