### ISSUE TITLE
UI ozone lamp power control

### ISSUE THREAD

**Issue by JustinLangridge** [msr-consulting/exscalabar#119]
Can we hook up this control please?

**Comment by lo-co** [comment]
What does this refer to?  All of the controls on the ``Common`` tab are currently hooked up.  The power array is sent via http as an unsigned byte which is converted to an array of bools which is then fed to the ``DAQmx Write`` VI.  Are you referring to something else?

**Comment by lo-co** [comment]
So, I tested this functionality and the message get to where it is supposed to be.  I think that you might be referring to something else.  I will dig around...

**Comment by lo-co** [comment]
OK...never mind.  I see what you want hooked up - ``O3 Lamp`` on the calibrations page.

**Comment by lo-co** [comment]
Added CVT entry in the ``calibration`` section called ``lamp_ratge``.

**Comment by lo-co** [comment]
Added entry in message ``Calibration::Change Frequency MSG::Do`` to change the CVT value.

We are going to make the value that is entered a rate rather than a percentage simply because I am not certain what the top rate is right now (no good documentation at present.

**Comment by JustinLangridge** [comment]
Currently we have an indicator for the lamp frequency on the UI cal page. it would be good to have a control here so that we can chnage lamp power when not operatign in an ozone auto-cycle

**Comment by lo-co** [comment]
Indicator only?  That shouldn't be.
