### ISSUE TITLE
Integrate web based UI into server

### ISSUE THREAD

**Issue by lo-co** [msr-consulting/exscalabar#120]
The requirements are that this must be light-weight (< 1 MB I believe) and that all files are properly referenced.  Already found a difference in the URL naming (using LiveReload in gulp produces a url without the `index.html`).

**Comment by lo-co** [comment]
After some jiggering of the code, this is up and running and all looks pretty good.  You can catch this on ``192.168.101.214:8001/xService/index.html``.  With this addition, the user will no longer be required to run ``gulp`` unless they want to make changes to the html or js.  

Need to make this a little more user friendly with gulp putting files into the proper folders...

**Comment by lo-co** [comment]
Not fully tested but appears to be working now.

**Comment by JustinLangridge** [comment]
Done. Closing
