### ISSUE TITLE
UI: CRDS laser duty cycle controls

### ISSUE THREAD

**Issue by JustinLangridge** [msr-consulting/exscalabar#76]
UI controls for setting laser duty cycle have no effect on output waveform (frequency and amplitude controls are working)

**Comment by JustinLangridge** [comment]
What is the status here? We don;t necessarily need ability to change duty cycle from the UI. Settign it in the ini is ok and then we can remove this control

**Comment by lo-co** [comment]
Sorry - didn't see this message.  The status is that this is not a UI thing.  It is strictly a server side issue.  Not initially built in because it creates issues.  Will change this.

**Comment by lo-co** [comment]
Need to test this but the lasers are not on.

**Comment by lo-co** [comment]
Works for me...
