### ISSUE TITLE
CRDS waveform write

### ISSUE THREAD

**Issue by JustinLangridge** [msr-consulting/exscalabar#78]
UI control for writing CRDS waveform data

**Comment by lo-co** [comment]
Added button but doesn't have supporting functionality on server side.  This is for actual ringdown data, not just taus.

**Comment by lo-co** [comment]
I know above I said not just taus, but going with the original theme, I am writing taus to file.  All of the backend code is there, just need to add the button.

**Comment by JustinLangridge** [comment]
Hi matt, this is ready for testing. Can you give information on data formats and location of saved files?

**Comment by JustinLangridge** [comment]
covered on a server issue. Closing.
